development:
  host: localhost
  database: twitter_re_development

test:
  host: localhost
  database: twitter_re_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>